-- [nfnl] init.fnl
require("defaults")
require("defaults")
require("plugins_setup")
require("colorscheme")
require("remaps")
require("fuzzy/fuzzy_finding")
require("language_server_config")
require("floatterm")
require("treesitter_setup")
require("hurl")
require("snippets.main")
return require("notes")
