require('defaults')
require('plugins_setup')
require('remaps')
require('colorscheme')
require('fuzzy/fuzzy_finding')
require('language_server_config')
require('treesitter_setup')
require('floatterm')
require('go')
require('hurl')

